# **CLASSIFICAÇÃO**
----
classificação usando sklearn

In [4]:
#Vamos começando importando as bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
#Agora vamos importar nosso CSV da pasta
df = pd.read_csv(r'C:\Users\Ademir\Desktop\BootCamp IGTI\ML\Módulo 3 - Seleção de Modelos de ML\diabetes.csv')
df.head()

preg  plas  pres  skin  insu  mass   pedi  age            class
0     6   148    72    35     0  33.6  0.627   50  tested_positive
1     1    85    66    29     0  26.6  0.351   31  tested_negative
2     8   183    64     0     0  23.3  0.672   32  tested_positive
3     1    89    66    23    94  28.1  0.167   21  tested_negative
4     0   137    40    35   168  43.1  2.288   33  tested_positive

In [12]:
#Agora que temos nosso Dataframe
#vamos analisar nosso tipo de informações
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   preg    768 non-null    int64  
 1   plas    768 non-null    int64  
 2   pres    768 non-null    int64  
 3   skin    768 non-null    int64  
 4   insu    768 non-null    int64  
 5   mass    768 non-null    float64
 6   pedi    768 non-null    float64
 7   age     768 non-null    int64  
 8   class   768 non-null    object 
dtypes: float64(2), int64(6), object(1)
memory usage: 54.1+ KB


In [13]:
#Agora vamos transformar nosso dados de teste em categóricos para 
#treinar de forma melhor o modelo
name_to_class = {
    'tested_positive': 1,
    'tested_negative': 0
}

#Agora substituindo no nosso dataframe
df['class'] = df['class'].map(name_to_class)
df.head()

preg  plas  pres  skin  insu  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [14]:
#Isso resolve o problema do dado categórico
df.describe()

preg        plas        pres        skin        insu        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age       class  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [15]:
#Agora vamos importar a biblioteca de separação de treino e teste
from sklearn.model_selection import train_test_split

In [16]:
#Separando os dados em treino e teste
xtrain, xtest, ytrain, ytest = train_test_split(df.iloc[:, :-1], df['class'], test_size = 0.25, random_state = 42)

In [17]:
#Vamos verificar se a separação dos dados foi feita de forma correta
xtrain.head()

preg  plas  pres  skin  insu  mass   pedi  age
357    13   129     0    30     0  39.9  0.569   44
73      4   129    86    20   270  35.1  0.231   23
352     3    61    82    28     0  34.4  0.243   46
497     2    81    72    15    76  30.1  0.547   25
145     0   102    75    23     0   0.0  0.572   21

In [18]:
ytrain

357    1
73     0
352    0
497    0
145    0
      ..
71     0
106    0
270    1
435    1
102    0
Name: class, Length: 576, dtype: int64

# **Agora temos que pegar um BASELINE**
---
Vamos gerar valores aleatórios como baseline

In [19]:
#Criando o baseline
baseline_pred = np.random.choice([0,1], size = len(ytest))
print(baseline_pred)

[0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 0
 1 1 1 0 1 1 0 0 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1 0 1 1
 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 0 1 0
 1 1 1 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 1 0 0 0 1 1 1 1
 1 1 1 1 0 1 0 1 1 0 1 1 1 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 0 1 0 1 0 0 1 1 0
 0 0 1 1 0 1 1]


In [21]:
#Agora que temos um baseline de números aleatórios vamos importar as metricas
#e testar
from sklearn import metrics

#Agora vamos calcular as metricas com baseline e comparar com as nossas 
#respostas do ytest
print('Matrix de confusão\n', metrics.confusion_matrix(ytest, baseline_pred))
print('\nAcurácia\n', metrics.accuracy_score(ytest, baseline_pred))
print('\nAcurária Balanceada por Classe\n', metrics.balanced_accuracy_score(ytest, baseline_pred))
print('\nPrecisão\n', metrics.precision_score(ytest, baseline_pred))
print('\nRevocação\n', metrics.recall_score(ytest, baseline_pred))
print('\nF1\n', metrics.f1_score(ytest, baseline_pred))

print('\nAUROC\n', metrics.roc_auc_score(ytest, baseline_pred))

Matrix de confusão
 [[59 64]
 [26 43]]

Acurácia
 0.53125

Acurária Balanceada por Classe
 0.5514316012725344

Precisão
 0.40186915887850466

Revocação
 0.6231884057971014

F1
 0.4886363636363636

AUROC
 0.5514316012725344


In [22]:
#Vamos usar uma métrica que apresenta todas as mais importante medidas
#de classificadores
print('Classification Report\n', metrics.classification_report(ytest, baseline_pred))

Classification Report
               precision    recall  f1-score   support

           0       0.69      0.48      0.57       123
           1       0.40      0.62      0.49        69

    accuracy                           0.53       192
   macro avg       0.55      0.55      0.53       192
weighted avg       0.59      0.53      0.54       192



# **KNN**
---

In [24]:
#vamos importar nosso modelo
from sklearn.neighbors import KNeighborsClassifier

In [26]:
#Agora vamos setar o nosso modelo
cls_knn = KNeighborsClassifier()
cls_knn.fit(xtrain, ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [27]:
#Agora que ele foi treinado, vamos testar e prever
pred_knn = cls_knn.predict(xtest)

In [30]:
#Agora vamos analisar o que foi gerado
df_knn_pred = pd.DataFrame({'Real':ytest, 'KNN':pred_knn})
df_knn_pred.head(10)

Real  KNN
668     0    1
324     0    0
624     0    0
690     0    1
473     0    0
204     0    1
97      0    0
336     0    0
568     0    1
148     0    1

In [31]:
#Agora vamos calcular as metricas com knn e comparar com as nossas 
#respostas do ytest
print('Matrix de confusão\n', metrics.confusion_matrix(ytest, pred_knn))
print('\nAcurácia\n', metrics.accuracy_score(ytest, pred_knn))
print('\nAcurária Balanceada por Classe\n', metrics.balanced_accuracy_score(ytest, pred_knn))
print('\nPrecisão\n', metrics.precision_score(ytest, pred_knn))
print('\nRevocação\n', metrics.recall_score(ytest, pred_knn))
print('\nF1\n', metrics.f1_score(ytest, pred_knn))

print('\nAUROC\n', metrics.roc_auc_score(ytest, pred_knn))

Matrix de confusão
 [[88 35]
 [31 38]]

Acurácia
 0.65625

Acurária Balanceada por Classe
 0.6330858960763521

Precisão
 0.5205479452054794

Revocação
 0.5507246376811594

F1
 0.5352112676056338

AUROC
 0.633085896076352


In [32]:
print('Classification Report\n', metrics.classification_report(ytest, pred_knn))

Classification Report
               precision    recall  f1-score   support

           0       0.74      0.72      0.73       123
           1       0.52      0.55      0.54        69

    accuracy                           0.66       192
   macro avg       0.63      0.63      0.63       192
weighted avg       0.66      0.66      0.66       192



# **SVM - Support Vector Machine**
---

In [34]:
#Vamos importar nosso modelo
from sklearn.svm import SVC

In [35]:
#Vamos treinar nosso modelo inicialmente
cls_svc = SVC(kernel='rbf') #kernel rbf é gaussiana
cls_svc.fit(xtrain, ytrain)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [37]:
pred_svc = cls_svc.predict(xtest)

df_svc_pred = pd.DataFrame({'Real':ytest,'SVC':pred_svc})
df_svc_pred.head(10)

Real  SVC
668     0    0
324     0    0
624     0    0
690     0    0
473     0    0
204     0    0
97      0    0
336     0    0
568     0    1
148     0    1

In [38]:
#Agora vamos calcular as metricas com svc e comparar com as nossas 
#respostas do ytest
print('Matrix de confusão\n', metrics.confusion_matrix(ytest, pred_svc))
print('\nAcurácia\n', metrics.accuracy_score(ytest, pred_svc))
print('\nAcurária Balanceada por Classe\n', metrics.balanced_accuracy_score(ytest, pred_svc))
print('\nPrecisão\n', metrics.precision_score(ytest, pred_svc))
print('\nRevocação\n', metrics.recall_score(ytest, pred_svc))
print('\nF1\n', metrics.f1_score(ytest, pred_svc))

print('\nAUROC\n', metrics.roc_auc_score(ytest, pred_svc))

Matrix de confusão
 [[106  17]
 [ 35  34]]

Acurácia
 0.7291666666666666

Acurária Balanceada por Classe
 0.6772711205372923

Precisão
 0.6666666666666666

Revocação
 0.4927536231884058

F1
 0.5666666666666667

AUROC
 0.6772711205372923


In [40]:
print('Classification Report\n', metrics.classification_report(ytest, pred_svc))

Classification Report
               precision    recall  f1-score   support

           0       0.75      0.86      0.80       123
           1       0.67      0.49      0.57        69

    accuracy                           0.73       192
   macro avg       0.71      0.68      0.68       192
weighted avg       0.72      0.73      0.72       192



#  **Random Forest Classifiers**
---

In [41]:
#O Coringa da classificação
#Vamos importar o modelo
from sklearn.ensemble import RandomForestClassifier

In [42]:
#Agora vamos treinar e prever o modelo
cls_floresta = RandomForestClassifier(n_estimators= 10, random_state=42)
cls_floresta.fit(xtrain, ytrain)
pred_floresta = cls_floresta.predict(xtest)

In [43]:
#Agora vamos montar um dataframe para análise

df_floresta_pred = pd.DataFrame({'Real':ytest,'RandomForest':pred_floresta})
df_floresta_pred.head(10)

Real  RandomForest
668     0             0
324     0             0
624     0             0
690     0             0
473     0             0
204     0             1
97      0             0
336     0             1
568     0             1
148     0             1

In [44]:
#Agora vamos calcular as metricas com RandomForest e comparar com as nossas 
#respostas do ytest
print('Matrix de confusão\n', metrics.confusion_matrix(ytest, pred_floresta))
print('\nAcurácia\n', metrics.accuracy_score(ytest, pred_floresta))
print('\nAcurária Balanceada por Classe\n', metrics.balanced_accuracy_score(ytest, pred_floresta))
print('\nPrecisão\n', metrics.precision_score(ytest, pred_floresta))
print('\nRevocação\n', metrics.recall_score(ytest, pred_floresta))
print('\nF1\n', metrics.f1_score(ytest, pred_floresta))

print('\nAUROC\n', metrics.roc_auc_score(ytest, pred_floresta))

Matrix de confusão
 [[97 26]
 [24 45]]

Acurácia
 0.7395833333333334

Acurária Balanceada por Classe
 0.72039589961117

Precisão
 0.6338028169014085

Revocação
 0.6521739130434783

F1
 0.6428571428571428

AUROC
 0.72039589961117


In [45]:
print('Classification Report\n', metrics.classification_report(ytest, pred_floresta))

Classification Report
               precision    recall  f1-score   support

           0       0.80      0.79      0.80       123
           1       0.63      0.65      0.64        69

    accuracy                           0.74       192
   macro avg       0.72      0.72      0.72       192
weighted avg       0.74      0.74      0.74       192

