# **Trabalho Prático do Módulo 3**

---
Vamos trabalhar com 3 datasets:

* diabetes_numeric.csv;
* bloodtransf.csv;
* wine.csv.
<br>No qual, vamos aplicar regressão, SVM e K-Means, respectivamente, para cada dataset.

In [1]:
#Primeiramente, vamos importar as bibliotecas mais usadas em ML
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

 1. Baixar os arquivos referentes as bases de dados e acessá-las pelo collab.

In [29]:
#Agora vamos carregar os datasets
df_blood = pd.read_csv (r'C:\Users\Ademir\Desktop\BootCamp IGTI\ML\Módulo 3 - Seleção de Modelos de ML\Trabalho Prático\bloodtransf.csv')
df_diabetes = pd.read_csv(r'C:\Users\Ademir\Desktop\BootCamp IGTI\ML\Módulo 3 - Seleção de Modelos de ML\Trabalho Prático\diabetes_numeric.csv')
df_wine = pd.read_csv(r'C:\Users\Ademir\Desktop\BootCamp IGTI\ML\Módulo 3 - Seleção de Modelos de ML\Trabalho Prático\wine.csv')

2. Obter informações sobre números de features e instâncias dos datasets.
3. Identificar a existência de dados faltantes nos datasets.

In [30]:
#Agora vamos tirar as informações de cada dataset
#Primeiro do Blood
df_blood.head()

V1  V2     V3  V4  Class
0   2  50  12500  98      2
1   0  13   3250  28      2
2   1  16   4000  35      2
3   2  20   5000  45      2
4   1  24   6000  77      1

In [31]:
df_blood.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      748 non-null    int64
 1   V2      748 non-null    int64
 2   V3      748 non-null    int64
 3   V4      748 non-null    int64
 4   Class   748 non-null    int64
dtypes: int64(5)
memory usage: 29.3 KB


In [32]:
#Diabetes
df_diabetes.head()

age  deficit  c_peptide
0   5.2     -8.1        4.8
1   8.8    -16.1        4.1
2  10.5     -0.9        5.2
3  10.6     -7.8        5.5
4  10.4    -29.0        5.0

In [33]:
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        43 non-null     float64
 1   deficit    43 non-null     float64
 2   c_peptide  43 non-null     float64
dtypes: float64(3)
memory usage: 1.1 KB


In [34]:
#Wine
df_wine.head()

class  Alcohol  Malic_acid   Ash  Alcalinity_of_ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Total_phenols  Flavanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280%2FOD315_of_diluted_wines  Proline  
0             5.64  1.04                            3.92     1065  
1             4.38  1.05                            3.40     1050  
2             5.68  1.03                            3.17     1185  
3             7.80  0.86                            3.45     1480  
4             4.32  1.04                            2.93      735

In [35]:
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   class                           178 non-null    int64  
 1   Alcohol                         178 non-null    float64
 2   Malic_acid                      178 non-null    float64
 3   Ash                             178 non-null    float64
 4   Alcalinity_of_ash               178 non-null    float64
 5   Magnesium                       178 non-null    int64  
 6   Total_phenols                   178 non-null    float64
 7   Flavanoids                      178 non-null    float64
 8   Nonflavanoid_phenols            178 non-null    float64
 9   Proanthocyanins                 178 non-null    float64
 10  Color_intensity                 178 non-null    float64
 11  Hue                             178 non-null    float64
 12  OD280%2FOD315_of_diluted_wines  178 

In [36]:
df_wine['class'].unique()

array([1, 2, 3], dtype=int64)

4. Separar os conjuntos de treino e teste, usando a função train_test_slipt, com test_size = 0.25 e random_state = 42.

In [37]:
#Agora vamos tratar os dados para trabalhar com eles e treinar os modelos
from sklearn.model_selection import train_test_split

<p style = 'font-size: 25px'><strong> Sabemos que queremos prever os dados as colunas:</strong></p><br>
1. Class para Wine;<br>
2. Class para Blood;<br>
3. C_peptide para Diabetes.
<p>Logo vamos separar os dados dessa forma e trabalhar com os mesmos desta forma.</p>

In [38]:
#Começando a separação de dados
xtrain_diab, xtest_diab, ytrain_diab, ytest_diab = train_test_split(df_diabetes.iloc[:,:-1],df_diabetes['c_peptide'], 
                                                                    test_size = 0.25, random_state = 42)

In [39]:
#Checando
xtrain_diab.head()

age  deficit
27  13.8    -11.9
31  12.4     -0.8
19   8.5     -0.2
17  11.5     -9.0
13   5.2     -4.5

In [40]:
ytrain_diab.head()

27    3.7
31    5.2
19    5.3
17    5.5
13    4.9
Name: c_peptide, dtype: float64

In [41]:
#Agora vamos fazer a separação para Blood
df_blood['Class'].unique()

array([2, 1], dtype=int64)

In [42]:
#Sabemos as classes, agora vamos binarizar o problema
mapa_para_blood = {
    1: 0,
    2: 1
}
df_blood['Class'] = df_blood['Class'].map(mapa_para_blood)
df_blood.head()

V1  V2     V3  V4  Class
0   2  50  12500  98      1
1   0  13   3250  28      1
2   1  16   4000  35      1
3   2  20   5000  45      1
4   1  24   6000  77      0

In [43]:
#Agora vamos fazer a separação dos dados para o blood

xtrain_blood, xtest_blood, ytrain_blood, ytest_blood = train_test_split(df_blood.iloc[:,:-1], df_blood['Class'],
                                                                       test_size = 0.25, random_state = 42)

In [44]:
#Checando
xtrain_blood.head()

V1  V2    V3  V4
24    9   9  2250  16
602   9   3   750  14
399  21   3   750  26
450  23   3   750  33
332  16   6  1500  35

In [45]:
ytrain_blood.head()

24     0
602    0
399    1
450    0
332    1
Name: Class, dtype: int64

In [47]:
#Por fim, vamos selecionar os diversos cluster de wine e vamos separar os dados
mapa_para_wine = {
    1: 0,
    2: 1,
    3: 2
}
df_wine['class'] = df_wine['class'].map(mapa_para_wine)

In [48]:
#Checando
df_wine.head()

class  Alcohol  Malic_acid   Ash  Alcalinity_of_ash  Magnesium  \
0      0    14.23        1.71  2.43               15.6        127   
1      0    13.20        1.78  2.14               11.2        100   
2      0    13.16        2.36  2.67               18.6        101   
3      0    14.37        1.95  2.50               16.8        113   
4      0    13.24        2.59  2.87               21.0        118   

   Total_phenols  Flavanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280%2FOD315_of_diluted_wines  Proline  
0             5.64  1.04                            3.92     1065  
1             4.38  1.05                            3.40     1050  
2             5.68  1.03                            3.17     1185  
3             7.80  0.86                            3.45     1480  
4             4.32  1.04                            2.93      735

In [86]:
#Vamos realizar a separação
y_label_wine = np.array(df_wine['class'])
data_wine = np.array(df_wine.drop('class', axis = 1))

In [88]:
#Checando a separação
y_label_wine

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2], dtype=int64)

In [89]:
data_wine

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [90]:
#Agora vamos fazer a sepração dos dados
xtrain_wine, xtest_wine, ytrain_wine, ytest_wine = train_test_split(data_wine, y_label_wine, 
                                                                   test_size = 0.25, random_state = 42)

In [92]:
#Checando
xtrain_wine

array([[1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       [1.208e+01, 2.080e+00, 1.700e+00, ..., 1.270e+00, 2.960e+00,
        7.100e+02],
       [1.242e+01, 4.430e+00, 2.730e+00, ..., 9.200e-01, 3.120e+00,
        3.650e+02],
       ...,
       [1.438e+01, 1.870e+00, 2.380e+00, ..., 1.200e+00, 3.000e+00,
        1.547e+03],
       [1.269e+01, 1.530e+00, 2.260e+00, ..., 9.600e-01, 2.060e+00,
        4.950e+02],
       [1.234e+01, 2.450e+00, 2.460e+00, ..., 8.000e-01, 3.380e+00,
        4.380e+02]])

In [93]:
ytrain_wine

array([0, 1, 1, 2, 0, 1, 0, 0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 1, 2, 0, 0, 0,
       2, 0, 0, 1, 2, 1, 0, 2, 1, 0, 2, 1, 1, 0, 1, 0, 0, 1, 0, 0, 2, 1,
       1, 1, 0, 1, 1, 1, 2, 2, 0, 1, 2, 2, 1, 1, 0, 1, 2, 2, 1, 2, 1, 1,
       1, 0, 0, 2, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1, 1, 1, 2, 2,
       1, 0, 0, 1, 2, 2, 0, 1, 2, 2, 2, 2, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0,
       2, 1, 0, 2, 2, 0, 0, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 0, 1,
       1], dtype=int64)

# **5. Importar o sklearn para:**

---

6. Aplicar à base diabetes_numeric.csv o modelo de regressão linear.

In [56]:
#Vamos importar a regressão e setar
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [57]:
#Agora vamos treinar o modelo e visualizar sua resposta
reg.fit(xtrain_diab, ytrain_diab)
pred_reg = reg.predict(xtest_diab)

#Vamos montar o dataframe para visualizar o primeiros resultados
df_pred_reg = pd.DataFrame({'Real': ytest_diab, 'Regressão': pred_reg})
df_pred_reg.head()

Real  Regressão
37   6.0   5.256343
24   5.7   5.355738
25   5.1   5.118052
36   5.1   4.716996
34   3.9   4.348632

7. Avaliar as métricas R2, MAE e MSE.

In [58]:
#Vamos importar as metricas para analisar essa regressão
from sklearn import metrics

In [60]:
#Aplicando as métricas para avaliar o modelo
print('R2: ', metrics.r2_score(ytest_diab, pred_reg))
print('\nMAE: ', metrics.mean_absolute_error(ytest_diab, pred_reg))
print('\nMSE: ', metrics.mean_squared_error(ytest_diab, pred_reg))

R2:  0.21880597788432865

MAE:  0.6107422323514548

MSE:  0.47452694731819717


8. Aplicar à base bloodtransf.csv o modelo SVC, com kernel=rbf.

In [69]:
#Importando o modelo SVC e setando
from sklearn.svm import SVC
svc = SVC(kernel = 'rbf')

In [70]:
#Agora vamos treinar o modelo e analisar as respotas
svc.fit(xtrain_blood, ytrain_blood)
pred_svc = svc.predict(xtest_blood)

#Agora vamos montar um pequeno df para visualizar as respostas
df_pred_svc = pd.DataFrame({'Real': ytest_blood, 'SVC': pred_svc})
df_pred_svc.head()

Real  SVC
580     0    0
356     0    0
133     0    0
250     0    0
299     0    0

9. Avaliar as métricas Acurácia, Precision, Recall, F1 e AUROC

In [71]:
#Agora vamos avaliar as métricas
print('Matriz de Confusão\n', metrics.confusion_matrix(ytest_blood, pred_svc))
print('\nAcurácia: ', metrics.accuracy_score(ytest_blood, pred_svc))
print('\nPrecision: ', metrics.precision_score(ytest_blood, pred_svc))
print('\nRecall: ', metrics.recall_score(ytest_blood, pred_svc))
print('\nF1: ', metrics.f1_score(ytest_blood, pred_svc))
print('\nAUROC: ',metrics.roc_auc_score(ytest_blood, pred_svc))

Matriz de Confusão
 [[139   0]
 [ 47   1]]

Acurácia:  0.7486631016042781

Precision:  1.0

Recall:  0.020833333333333332

F1:  0.04081632653061225

AUROC:  0.5104166666666666


10. Aplicar à base wine.csv o modelo kmeans.

In [94]:
#Agora vamos importar o modelo e seta-lo
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)

In [95]:
#Agora vamos treinar o modelo e fazer sua previsão
kmeans.fit(xtrain_wine)
pred_kmeans = kmeans.predict(xtest_wine)

#Agora vamos criar um df para visualizar as respostas
df_pred_kmeans = pd.DataFrame({'Real': ytest_wine, 'KMeans': pred_kmeans})
df_pred_kmeans.head()

Real  KMeans
0     0       2
1     0       0
2     2       1
3     0       0
4     1       1

11. Identificar o número de clusters mais adequado de acordo com o dataset

In [98]:
np.unique(y_label_wine)

array([0, 1, 2], dtype=int64)

12. Avaliar as métricas Coeficiente de Silhueta, Davies-Bouldin Score e Mutual Information.

In [99]:
#Agora vamos avaliar as métricas de cluster
from sklearn.metrics import cluster

In [104]:
#Agora vamos Avaliar as métricas
print('Coeficiente de Silhueta: ', metrics.silhouette_score(ytest_wine.reshape(1,-1), pred_kmeans.reshape(1, -1)))
print('\nDavies-Bouldin: ', metrics.davies_bouldin_score(ytest_wine, pred_kmeans))
print('\nMutual Information: ', metrics.mutual_info_score(ytest_wine, pred_kmeans))

ValueError: bad input shape (1, 45)